<a href="https://colab.research.google.com/github/boguslaw-major/Data-Science/blob/master/rownanie_liniowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#rozwiązujemy układ rownian linowych 2x+4y=10 i x-y=-1
import numpy as np

A=np.array([[2,4],[1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [5]:
B=np.array([[10],[-1]])
print(B)


[[10]
 [-1]]


In [7]:
A_inv=np.linalg.inv(A)
X=np.dot(A_inv,B)
X

array([[1.],
       [2.]])

In [8]:
X.shape

(2, 1)